## ---------------------------
## Purpose: Functions to calculate normalized ODs, mean MIC and mean SMG per strain 
## Author: Nancy Scott
## Email: scot0854@umn.edu
## ---------------------------
## Notes: plotting moved to different script 
## ---------------------------
options(scipen = 999) 
## ---------------------------
## load packages
library(readxl)
library(tidyverse)
library(gtools)
## ---------------------------
# Assumes tidied data with associated metadata (long format)

# Calculate per-plate mean background, correct background, 
# normalize to no-drug control per plate,
# and calculate combined mean of all plates:
calculate_od <- function(tidy_mic) {
  plate_blank <- tidy_mic %>%
    # control for spreadsheet layout (cols vs rows of samples)
    filter(concentration == "blank" | strain == "blank") %>%
    filter(OD600 < 0.2) %>% # remove likely contaminated wells
    group_by(plate) %>%
    summarise(mean_blank = mean(OD600))


  corrected_od <- tidy_mic %>%
    inner_join(plate_blank, by = "plate") %>%
    filter(concentration != "blank") %>%
    filter(strain != "blank") %>% # don't need blanks anymore, shrink dataframes
    group_by(plate) %>%
    mutate(corrected_OD600 = OD600 - mean_blank)
       
  norm_od <- corrected_od %>%
    group_by(plate,strain) %>%
    mutate(norm_OD600 = corrected_OD600/corrected_OD600[concentration=="0" | concentration=="0.0"])

  final_od <- norm_od %>%
    group_by(strain, concentration) %>%
    summarize(mean_norm_OD = round(mean(norm_OD600), digits = 3), sd_norm_od = sd(norm_OD600)) 
  
  final_od$concentration <- fct_drop(final_od$concentration) #drop unused levels
  # sort concentration from highest to lowest 
  final_od <- final_od[mixedorder(final_od$strain),] # alphabetical sorting
  
  final_od

}

# Determine MIC per strain: 
# Required arguments: final_od dataframe created by calculate_od function
# and numeric MIC cutpoint, e.g. mic_cutpoint=0.5 for FLC or mic_cutpoint=0.9 for amphotericin B
mic <- function(final_od, mic_cutpoint){
  mic_cut_high <- final_od %>%
    group_by(strain) %>%
    filter(concentration != "0") %>%     
    filter(min(mean_norm_OD) > mic_cutpoint) %>%
    slice_tail(n = 1)   
  mic_cut_low <- final_od %>%
      group_by(strain) %>%
      filter(concentration != "0") %>%
      slice(which(mean_norm_OD <= mic_cutpoint)) %>%
      slice_head(n=1)
      mic_cut <- rbind(mic_cut_high, mic_cut_low)
  mic_cut <- mic_cut[mixedorder(mic_cut$strain),]
  mic_cut
}

# Identify wells to include in SMG calculations:
# Required arguments: final_od dataframe created by calculate_od function
# and numeric cutpoint used for mic function.
smg_input <- function(final_od, mic_cutpoint){
    mic_for_48 <- final_od %>%
      slice(which(mean_norm_OD <= mic_cutpoint)) %>%
      slice_head(n = -1) %>%
      select(strain, concentration)
    mic_for_48
}

# SMG subsetting and calculation:
# Includes ifelse statement to set SMG to 0 if mean is below 0.
# Required arguments: final_od calculated from 48-hour spreadsheet 
# and mic_for_48 dataframe generated by smg_input function.
smg_subset <- function(final_od48, mic_for_48){
    final_od48 %>%
    inner_join(mic_for_48, by = c("strain","concentration")) %>%
    group_by(strain) %>%
    summarize(mean_48 = round(mean(mean_norm_OD), digits = 3)) %>%
      mutate(mean_48 = ifelse(mean_48 < 0, 0, mean_48))
}
